name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment when pushing to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run predeploy # runs build as defined in package.json

      - name: Deploy to gh-pages
        run: npm run deploy # pushes ./build to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
